services:
  client:
    build:
      context: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - ./client/public:/app/public
      - ./client/package.json:/app/package.json
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: lastProject
      POSTGRES_USER: lastProject_user
      POSTGRES_PASSWORD: lastProject
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
